### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by Greatguy2** [kemargrant/c4d#13]
Please help me cant start bot. Maybe you can tell me what should i change?

user@ubuntu:~/c4d$ nodejs --version
v11.2.0

user@ubuntu:~/c4d$ node main.js
Database Not Found
Binance Pair Error: undefined

MongoDB

user@ubuntu:~/c4d$ mongo --port 27017
MongoDB shell version: 3.2.21
connecting to: 127.0.0.1:27017/test
> show dbs;
admin  0.000GB
arb    0.000GB
local  0.000GB

Config:
"Binance":
		{
			"apikey":"hiden",
			"secretkey":"hiden",
			"enabled":true,
			"pairs":[{
			"liquidTrades":true,
			"lowerLimit1":100.2,
			"lowerLimit2":99,
			"optimalTrades":true,
			"pair1":"ltcbtc",
			"pair2":"btcusdt",
			"pair3":"ltcusdt",
			"upperLimit1":100.5,
			"upperLimit2":99.99
			}]
		},
	"Bittrex":
		{
			"apikey":"Bittrex_API_Key",
			"secret":"Bittrex_API_Secret",
			"enabled":false,
			"liquidTrades":true,
			"lowerLimit":98.3,
			"minimum":0.001,
			"pair1":"BTC-XXX",
			"pair2":"USDT-BTC",
			"pair3":"USDT-XXX",		
			"percentage1":1,
			"percentage2":0.5,					
			"saneTrades":true,
			"upperLimit":101.79,
			"viewBook":false
		},
	"Config":
		{
			"key":"Secret Private Key",	
			"logs":3,
			"port":7071,
			"useWasm":false
		},
	"Email":
		{
			"addr":"Recipient_Email_Address",
			"host_smtp":"Email_SMTP_IP_Address",
			"use":false,
			"usr":"Email Account Address",
			"pwd":"Email Password"		
		},
	"MongoDB":
		{
			"db_string":"mongodb://admin1:1234@localhost:27017/arb",
			"connect":true
		},	
	"Slack":
		{
			"channel":"Slack_Channel",
			"hook":"Slack_Webhook",
			"use":false,
			"usr":"Slack_user_to_notify"
		},
	"Swing":
		{
			"amount":0.001,
			"pair":"BTC-XXX",
			"rate":60000,
			"swing":0.02,
			"swingTrade":false
		}		
}
```

**Comment by kemargrant** [comment]
Binance pair format requires an underscore in between currencies ie ltcbtc should be ltc_btc

**Comment by Greatguy2** [comment]
I have changed pair format but still have problem with DB and nothing happens.

Please assist what should i do with config?

user@ubuntu:~/c4d$ node main.js
Database Not Found
^C
user@ubuntu:~/c4d$ node main.js
Database Not Found
^C
user@ubuntu:~/c4d$

**Comment by kemargrant** [comment]
You should confirm with a mongodb client that your database is configured correctly. It is possible to use the bot by setting connect to false, however trade history is not saved.
