### ISSUE TITLE
DB only for bittrex

### ISSUE THREAD

**Issue by Memoi** [kemargrant/c4d#15]
Hi,

I see in your code that the mongoDB is only for Bittrex config, do we loose some feature if we don't use it with Binance ?

Thanks

**Comment by kemargrant** [comment]
!??! The mongodb is used for both binance/bitterex. 
If you want to use c4dc and get stats on your trades then  you need to configure a mongodb. If you want to use the experimental (swing) feature the you need to use mongodb.

**Comment by Memoi** [comment]
I ask this because the table are named with "Bittrex" and they are empty: 

[pic](http://imgur.com/a/NLFRCDD)

Plus, there is this message : 
DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

**Comment by Memoi** [comment]
What is the function of Swing please ?

**Comment by kemargrant** [comment]
The repo was originally created with a Bittrex Bot in mind, during the next major cleanup the mongdb scheme **should** be renamed.
The swing feature helps you vibrate in tune with the market...buying high and selling low within a specified percentage. 
It doesn't work well when there are wild swings which are common in crypto marketplace. I would not recommend trying to use this feature. I have contemplated removing it all together.
