### ISSUE TITLE
Sub-Optimal Trade not appear

### ISSUE THREAD

**Issue by Memoi** [kemargrant/c4d#17]
Hi,

Sub-Optimal Trade appear for me only with this conf :

"pair1":"eth_btc",
"pair2":"btc_usdt",
"pair3":"eth_usdt",

but not with this one :

"pair1":"vet_btc",
"pair2":"btc_usdt",
"pair3":"vet_usdt"

It's normal ?

Thanks for your help

<----------->
Sub-Optimal Trade:Binance Bot: 99.989% Tue Apr 09 2019 08:33:27 
4.919eth => 858.90659 usdt @174.61
858.9057745399998usdt => 0.166423 btc @5160.98
0.16640485btc => 4.920 eth @0.033829

**Comment by kemargrant** [comment]
Sub-optimal trades can appear depending on the pricing of each asset in the arbitrage and how they compare to the other 2. The specific currency doesn't matter.
