### ISSUE TITLE
A

### ISSUE THREAD

**Issue by KamillusWabner** [kemargrant/c4d#2]
I set everything up and the software is running.
But it's not making any trades. Do I have to change something in the settings?
Am I right that it should make trades and is profitable when it crosses the top line (100.75)?
Why is that chart sometimes green and sometimes red?

**Comment by kemargrant** [comment]
@KamillusWabner 
1)You are correct unless the percentage deviates ~0.75% from 100% the trade would not be profitable.

2)It is possible to go many hours without trading depending on the volatility and volume of the currency you are trying to arbitrage. I have gone more than a day without c4d making trade. The average I would say is ~4.5 trades/day. However, with the recent volatility many more were made.
![image](https://user-images.githubusercontent.com/2120365/33512425-46757e5c-d6fe-11e7-9cce-3b06870b2f02.png)

2a)There is a setting I will expose in the future to allow the bot to trade even on a thin order book. The bot currently looks at the books to make sure there is enough liquidity in the market to quickly execute the arbitrage.

3)The green line is when you just connect to the bot and it sends old information to the browser. When the chart goes red the information is fresh.

**Comment by KamillusWabner** [comment]
The trade chart actually shows trades. For today there were already 18. But
there were no actual trades made in my bittrex account. How can I solve
this?

When I get this working I‘ll definitely send you some satoshis.


Thank you for your great help and best regards!

>

**Comment by kemargrant** [comment]
Does your Bittrex API key have the ability to read info and trade limit?
If you have any console error messages please paste the output.

**Comment by KamillusWabner** [comment]
I forgot to turn trade limit on.
I changed it and that was the problem even though I got no console error message.

But I got a new issue. The last order (back to btc) stays always open and does not filled instantly and thus its not profitable or I have to wait until I gets filled. I thought c4d is making all three trades at the same time. Do you know why this happens and how I can prevent this from happening again.

![skizze 6](https://user-images.githubusercontent.com/25422202/33529814-1bffa796-d876-11e7-9602-94f090953be3.png)
![skizze 7](https://user-images.githubusercontent.com/25422202/33529907-2b058e08-d877-11e7-8059-dcf82e6eb3f9.png)

**Comment by kemargrant** [comment]
Well I am glad your problem is fixed.
As to why your order doesn't fill immediately...that is currently the 100btc question. No one knows how the market will move. I have gone through a couple of different iterations of c4d. This one so far leaves fewer trades left behind(none so far). Previous iteration could leave 5% of trades left behind(or taking days to fill) which is pretty bad.

The next few updates will actually track how long trades are left open and provide stats by using the mongodb database.

**Comment by KamillusWabner** [comment]
What I though is that c4d does all three trades at the exact same time at
the exact rate. So this would not happen.

Another question that I have is: Are you thinking about adding the ability
of useing eth/btc as the main market. I think there are often some good
profitability’s.

**Comment by kemargrant** [comment]
Some orders are buys and some orders are sells.
Depending on how volatility,liquidity, and direction of the market your trade could get instantly filled or left behind in the dust. 

I am looking to add more flexibility in the future for the pairs used however Bittrex is a bit inflexible with their markets so I doubt it would be possible.
What pairs did you have in mind?

Liqui/Binance for example have more market flexibility.
