### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by onthetunnel** [kemargrant/c4d#5]
hello , when i run node main.js and i got TypeError: Cannot read property '0' of undefined
  at .....CryptoBot.binanceFormatPairs c4d.js:725:77 also CryptoBot.binancePrecision. then  c4d.js:74:8

Hope you can help me Thanks!

**Comment by kemargrant** [comment]
Are you trading on Binance?

**Comment by onthetunnel** [comment]
Hello Dear , yes ..and got this error.. hope you can help me ...Thanks You!

**Comment by kemargrant** [comment]
This is fixed on the develop branch, however I have to do some more testing before I can merge develop into the master branch.

**Comment by onthetunnel** [comment]
Ok , hope you can fix this , is awesome project for crypto , Thanks You!

**Comment by kemargrant** [comment]
Please post your config.json file.....without your private keys

**Comment by onthetunnel** [comment]
Hello Dear Kemargrant , i just put my binance api into the config.json and no edit other word on this config file ...after doing this i use node main.js run the project..and get the typeerror... hope you can help me .. Thanks You!

**Comment by kemargrant** [comment]
You need to edit the binance pairs to your liking. Tell me some currencies you have in your portfolio and I will give you an example of how to arrange your config.json

**Comment by onthetunnel** [comment]
Like  NANO , TRON , IOTA , EOS , FUN but how to edit the config for best profitable? can you share your config if you dont mind ... anyway  Thanks you for helping me !

**Comment by kemargrant** [comment]
You can configure your Binance pairs to look like this:

"pairs":[{	        "liquidTrades":true,
			"lowerLimit1":100.2,
			"lowerLimit2":99,
			"optimalTrades":true,
			"pair1":"iota_btc",
			"pair2":"btc_usdt",
			"pair3":"iota_usdt",
			"upperLimit1":100.5,
			"upperLimit2":99.99
			}]
Closing this issue because this is not an issue.
Linking to https://github.com/kemargrant/c4d/issues/4
