### ISSUE TITLE
multiple pair for triangular arbitrage?

### ISSUE THREAD

**Issue by onthetunnel** [kemargrant/c4d#7]
hello,  can i know how can i edit the config for auto trading multiple pair/road of triangular arbitrage? 
like : eos , nano , iota and more ... Thanks You!

**Comment by kemargrant** [comment]
Multiple pairs can be used **"only"** with Binance and has been lightly tested.
Ensure that each pair1 is unique and does not appear multiple times.
"pairs":[
{"liquidTrades":true,
"lowerLimit1":100.2,
"lowerLimit2":99,
"optimalTrades":true,
"pair1":"iota_btc",
"pair2":"btc_usdt",
"pair3":"iota_usdt",
"upperLimit1":100.5,
"upperLimit2":99.99},
{"liquidTrades":true,
"lowerLimit1":100.2,
"lowerLimit2":99,
"optimalTrades":true,
"pair1":"eos_btc",
"pair2":"btc_usdt",
"pair3":"eos_usdt",
"upperLimit1":100.5,
"upperLimit2":99.99},
{"liquidTrades":true,
"lowerLimit1":100.2,
"lowerLimit2":99,
"optimalTrades":true,
"pair1":"nano_bnb",
"pair2":"nano_btc",
"pair3":"bnb_btc",
"upperLimit1":100.5,
"upperLimit2":99.99},
{"liquidTrades":true,
"lowerLimit1":100.2,
"lowerLimit2":99,
"optimalTrades":true,
"pair1":"iota_btc",
"pair2":"btc_usdt",
"pair3":"iota_usdt",
"upperLimit1":100.5,
"upperLimit2":99.99},
]
