### ISSUE TITLE
Bot trying to trade more than is in account

### ISSUE THREAD

**Issue by RcrossF** [kemargrant/c4d#9]
The bot attempts all trades with more ETH than I have in my wallet resulting in "Wallet Balance Low". I'm running with 0.10265276 ETH, 0.01552706 BTC and 94.7296721 USDT in my binance account but every trade it tries are worth 0.5 ETH or more. Part of the log is shown here: https://i.imgur.com/IkSiLbD.png. I'm using the pairs eth_btc, btc_usdt, eth_usdt. Minimum ETH and BTC orders are set to 0.001.

**Comment by kemargrant** [comment]
This is not documented clearly perhaps. You need to change the "Trades < 100% Upper Limit" to something below 99.98% so trades starting with eth => usdt will use less eth.
